service: clicks-tracker-table

custom:
  stage: ${{opt:stage, self:provider.stage}}
  tables:
    tracker: ${{self:custom.stage}}-clicksTracker
  deletionPolicy:
    predev: Delete
    dev: Delete
    staging: Retain
    prod: Retain
  profiles:
    predev: default
    dev: clicks-tracker-dev
    staging: clicks-tracker-staging
    prod: clicks-tracker-prod
provider:
  name: aws
  region: us-east-1
  stage: predev

  variableSyntax: "\\${{([ ~:a-zA-Z0-9._@\\'\",\\-\\/\\(\\)]+?)}}"
  profile: ${{self:custom.profiles.${{self:custom.stage}}}}
resources:
  Resources:
    ClicksTracker:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: ${{self:custom.deletionPolicy.${{self:custom.stage}}}}
      Properties:
        TableName: ${{self:custom.tables.tracker}}
        AttributeDefinitions:
          - AttributeName: "PK"
            AttributeType: "S"
          - AttributeName: "SK"
            AttributeType: "S"
          - AttributeName: "ip"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "PK"
            KeyType: "HASH"
          - AttributeName: "SK"
            KeyType: "RANGE"
        GlobalSecondaryIndexes:
          - IndexName: "gsiIp"
            KeySchema:
              - AttributeName: "ip"
                KeyType: "HASH"
            Projection:
              ProjectionType: KEYS_ONLY

        BillingMode: PAY_PER_REQUEST
  Outputs:
    ClicksTrackerTableArn:
      Value:
        Fn::GetAtt:
          - ClicksTracker
          - Arn
      Export:
        Name: ${{self:custom.stage}}-clicksTracker
